version: "3"
services:
    php: 
        image: 450453892/php
        container_name: zj_php
        ports: 
         - 9000:9000
        volumes: 
         - "${SOURCE_DIR}:/www"
         - "${PHP_DIR}:/usr/local/etc/php"
         
    nginx: 
        image: nginx
        container_name: zj_nginx
        ports: 
         - 80:80
        working_dir: /www
        volumes: 
         - "${NGINX_CONFD_DIR}:/etc/nginx/conf.d"
         - "${SOURCE_DIR}:/www"