php: 
    image: php:v3
    ports: 
     - "127.0.0.1:9000:9000"
    volumes: 
     - "D:/phpstudy_zj/WWW:/www"
     - "D:/phpstudy_zj/docker/php:/usr/local/etc/php/"
     
nginx: 
    image: nginx
    links: 
     - php
    ports: 
     - "127.0.0.1:80:80"
    working_dir: /www
    volumes: 
     - "D:/phpstudy_zj/docker/nginx/conf/conf.d:/etc/nginx/conf.d"
     - "D:/phpstudy_zj/WWW:/www"