services:
    php: 
        image: php:v71
        container_name: zj_php
        ports: 
         - 9000:9000
         - 8686:8686
         - 8787:8787
         - 7533:7533
        volumes: 
         - "${SOURCE_DIR}:/www"
         - "${PHP_DIR}:/usr/local/etc/php"
         
    nginx: 
        image: nginx
        container_name: zj_nginx
        ports: 
         - 8080:80
        working_dir: /www
        volumes: 
         - "${NGINX_CONFD_DIR}:/etc/nginx/conf.d"
         - "${SOURCE_DIR}:/www"
         
    mysql:
        image: mysql/mysql-server
        container_name: zj_mysql
        environment: 
            MYSQL_ROOT_PASSWORD: 123456
        command:
          --default-authentication-plugin=mysql_native_password
          --character-set-server=utf8mb4
          --collation-server=utf8mb4_general_ci
          --explicit_defaults_for_timestamp=true
          --lower_case_table_names=1
          --max_allowed_packet=128M;
          --bind-address=0.0.0.0
        ports: 
         - 3306:3306
        volumes:
         - "${MYSQL}:/var/lib/mysql"
         - "${MYSQL_CONF}:/etc/mysql/conf.d"